# Prometheus configuration for Document Analyzer

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'document-analyzer'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Rule files
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Main API service
  - job_name: 'document-analyzer-api'
    static_configs:
      - targets: ['api:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MySQL exporter (if installed)
  - job_name: 'mysql'
    static_configs:
      - targets: []
        # - mysql-exporter:9104

  # Redis exporter (if installed)
  - job_name: 'redis'
    static_configs:
      - targets: []
        # - redis-exporter:9121
